# Generated by Django 4.2.19 on 2025-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer', models.IntegerField()),
                ('knowledge', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('F&D', 'Food and Drink'), ('H', 'Health'), ('WB', 'Wellbeing'), ('W', 'Water'), ('WA', 'Waste'), ('N&B', 'Nature and Biodiversity'), ('T', 'Transport')], max_length=3)),
            ],
        ),
    ]
