# Generated by Django 5.0.3 on 2025-03-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[
                    ("F&D", "Food and Drink"),
                    ("HWB", "Health and Wellbeing"),
                    ("W", "Water"),
                    ("WA", "Waste"),
                    ("N&B", "Nature and Biodiversity"),
                    ("E", "Energy"),
                ],
                default=0,
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
