# Generated by Django 4.2.19 on 2025-02-21 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('F&D', 'Food and Drink'), ('H', 'Health'), ('WB', 'Wellbeing'), ('W', 'Water'), ('WA', 'Waste'), ('N&B', 'Nature and Biodiversity'), ('T', 'Transport')], max_length=3)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('E', 'Epic'), ('L', 'Legendary')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_monsters', to='users.monster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_monsters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
