# Generated by Django 4.2.19 on 2025-02-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='challenges_completed',
            field=models.IntegerField(default=0),
        ),
    ]
