# Generated by Django 5.0.3 on 2025-03-17 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_admin",
        ),
    ]
